project_id = "kttofcsxdrevdqzmrgqg"

[functions.parse-bancolombia-pdf]
verify_jwt = false

[functions.send-contact]
verify_jwt = false

[functions.create-wompi-checkout]
verify_jwt = false

[functions.wompi-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.parse-invoice-pdf]
verify_jwt = false

[functions.start-invoice-processing]
verify_jwt = false
