import type { PlanData } from './PricingCard';

export const plans: PlanData[] = [
  {
    id: 'demo',
    name: 'Demo',
    monthlyPrice: 0,
    period: 'Para siempre',
    description: 'Para probar AluminIA con un extracto real',
    features: [
      '1 PDF único (para siempre)',
      '1 cuenta bancaria',
      'Clasificación automática de movimientos',
      'Conciliación manual',
      'Dashboard básico',
      'Exportación a Excel',
    ],
    cta: 'Probar gratis',
    ctaAction: 'signup',
    highlighted: false,
    note: null,
    badge: null,
  },
  {
    id: 'basico',
    name: 'Básico',
    monthlyPrice: 399000,
    period: 'COP / mes',
    description: 'Para negocios en crecimiento',
    features: [
      '2 PDFs mensuales',
      '1 cuenta bancaria',
      '1 usuario incluido',
      'Dashboard completo',
      'Conciliaciones automáticas aproximadas',
      'IVA y retenciones estimadas',
      'Historial hasta 2 años',
      'Exportación a Excel',
      'Análisis financiero con IA',
      'Coach financiero con IA',
    ],
    cta: 'Suscribirme al plan Básico',
    ctaAction: 'wompi-basico',
    highlighted: false,
    note: 'Cálculos fiscales aproximados desde movimientos bancarios',
    badge: null,
  },
  {
    id: 'empresarial',
    name: 'Empresarial',
    monthlyPrice: 699000,
    period: 'COP / mes',
    description: 'Para empresas que facturan y quieren control total',
    features: [
      'PDFs ilimitados',
      'Hasta 2 cuentas bancarias',
      '2 usuarios (Administrador y Auxiliar)',
      'Módulo de Facturas DIAN',
      'Conciliación real por número de factura',
      'IVA, ReteICA y ReteFuente desde facturación',
      'Resumen DIAN mensual',
      'Historial ilimitado',
      'Reportes avanzados con IA',
      'Coach financiero con IA',
      'Área de Inventario integrada',
      'Descuento automático de inventario desde facturación',
      'Soporte prioritario',
    ],
    cta: 'Activar Empresarial',
    ctaAction: 'wompi-empresarial',
    highlighted: true,
    note: 'Convierte tus facturas en control financiero y de inventario automático.',
    badge: 'Más completo',
  },
];
