// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Implicit flow: recovery/magic links carry tokens in the URL hash instead of
    // a PKCE code. PKCE requires code_verifier in localStorage of the same browser
    // session that initiated the request — which fails for admin-sent emails or
    // cross-browser clicks. Implicit flow has no such dependency.
    flowType: 'implicit',
  }
});